apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: production
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: 20s
      count: 3
      successCondition: result[0] >= 0.99
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus-server.monitoring.svc:9090
          query: |
  (
    sum(rate(nginx_ingress_controller_requests{ingress="demo-api-ingress",status!~"[45].*"}[5m]))
  )
  /
  (
    sum(rate(nginx_ingress_controller_requests{ingress="demo-api-ingress"}[5m])) > 0
  )